server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona tudo para o index.html (Necessário para o React Router DOM)
        try_files $uri $uri/ /index.html;
    }
}
